import winston from 'winston';

// Emoji to text mapping for Windows compatibility
const emojiMap: Record<string, string> = {
  '🤖': '[AI]',
  '📋': '[PLAN]',
  '✅': '[OK]',
  '❌': '[ERR]',
  '⚠️': '[WARN]',
  '⏳': '[WAIT]',
  '🔄': '[LOOP]',
  '✏️': '[EDIT]',
  '📝': '[WRITE]',
  '🔍': '[SEARCH]',
  '💡': '[IDEA]',
  '🎯': '[TARGET]',
  '📊': '[STAT]',
  '🚀': '[START]',
  '💥': '[CRASH]',
  '📦': '[PKG]',
  '🌐': '[WEB]',
  '🔧': '[FIX]',
  '🎨': '[DESIGN]',
  '📚': '[DOC]',
  '🔗': '[LINK]',
  '📁': '[FILE]',
  '🔨': '[BUILD]',
  '🧪': '[TEST]',
  '📈': '[UP]',
  '📉': '[DOWN]',
  '⏱️': '[TIME]',
  '🐛': '[BUG]',
  '🔒': '[LOCK]',
  '🔓': '[UNLOCK]',
  '📢': '[INFO]',
  '🎉': '[DONE]',
  '🚫': '[BAN]',
  '✨': '[NEW]',
  '🗑️': '[DEL]',
  '📤': '[OUT]',
  '📥': '[IN]',
  '📄': '[PAGE]',
  '📃': '[LIST]',
  '📜': '[LOG]',
  '🏷️': '[TAG]',
  '📌': '[PIN]',
  '📍': '[LOC]',
  '🔖': '[BOOK]',
  '📎': '[CLIP]',
  '🖇️': '[LINKS]',
  '📐': '[RULE]',
  '📏': '[LINE]',
  '✂️': '[CUT]',
  '🗃️': '[BOX]',
  '🗄️': '[CAB]',
  '📰': '[NEWS]',
  '🗞️': '[PAPER]',
  '📑': '[BOOKMARK]',
  '💰': '[MONEY]',
  '💴': '[YEN]',
  '💵': '[USD]',
  '💶': '[EURO]',
  '💷': '[POUND]',
  '💸': '[CASH]',
  '💳': '[CARD]',
  '🧾': '[BILL]',
  '💹': '[CHART]',
  '✉️': '[MAIL]',
  '📧': '[EMAIL]',
  '📨': '[INMAIL]',
  '📩': '[OUTMAIL]',
  '📫': '[MAILBOX]',
  '📪': '[MAILBOX2]',
  '📬': '[OPENBOX]',
  '📭': '[EMPTYBOX]',
  '📮': '[POST]',
  '🗳️': '[VOTE]',
  '✒️': '[PEN]',
  '🖋️': '[PEN2]',
  '🖊️': '[PEN3]',
  '🖌️': '[BRUSH]',
  '🖍️': '[CRAYON]',
  '💼': '[BAG]',
  '📂': '[OPEN]',
  '🗂️': '[INDEX]',
  '📅': '[DATE]',
  '📆': '[CAL]',
  '🗒️': '[NOTE]',
  '🗓️': '[CAL2]',
  '📇': '[CARD]',
  '🔏': '[PRIV]',
  '🔐': '[CLOSED]',
  '🔑': '[KEY]',
  '🗝️': '[KEY2]',
  '⛏️': '[PICK]',
  '⚒️': '[TOOL]',
  '🛠️': '[TOOL2]',
  '🗡️': '[DAGGER]',
  '⚔️': '[SWORD]',
  '🔫': '[GUN]',
  '🏹': '[BOW]',
  '🛡️': '[SHIELD]',
  '🔩': '[NUT]',
  '⚙️': '[GEAR]',
  '🗜️': '[CLAMP]',
  '⚖️': '[SCALE]',
  '🦯': '[PROBE]',
  '⛓️': '[CHAIN]',
  '🧰': '[TOOLBOX]',
  '🧲': '[MAGNET]',
  '⚗️': '[ALE]',
  '🧫': '[PETRI]',
  '🧬': '[DNA]',
  '🔬': '[MICRO]',
  '🔭': '[TELE]',
  '📡': '[ANT]',
  '💉': '[NEEDLE]',
  '🩸': '[DROP]',
  '💊': '[PILL]',
  '🩹': '[BAND]',
  '🩺': '[STETHO]',
  '🌡️': '[TEMP]',
  '🧹': '[BROOM]',
  '🧺': '[BASKET]',
  '🧻': '[PAPER]',
  '🚽': '[TOIL]',
  '🚰': '[WATER]',
  '🚿': '[SHOWER]',
  '🛁': '[BATH]',
  '🛀': '[BATH2]',
  '🧼': '[SOAP]',
  '🪒': '[RAZOR]',
  '🧽': '[SPONGE]',
  '🧴': '[LOTION]',
  '🛎️': '[BELL]',
  '🚪': '[DOOR]',
  '🪑': '[CHAIR]',
  '🛋️': '[COUCH]',
  '🛏️': '[BED]',
  '🛌': '[SLEEP]',
  '🧸': '[BEAR]',
  '🖼️': '[PIC]',
  '🛍️': '[SHOP]',
  '🛒': '[CART]',
  '🎁': '[GIFT]',
  '🎈': '[BALL]',
  '🎏': '[FLAGS]',
  '🎀': '[RIBBON]',
  '🎊': '[CONFETTI]',
  '🎎': '[DOLL]',
  '🏆': '[TROPHY]',
  '🏅': '[MEDAL]',
  '🥇': '[GOLD]',
  '🥈': '[SILVER]',
  '🥉': '[BRONZE]',
  '⚽': '[BALL]',
  '🏀': '[BALL2]',
  '🏈': '[BALL3]',
  '⚾': '[BALL4]',
  '🥎': '[BALL5]',
  '🎾': '[BALL6]',
  '🏐': '[BALL7]',
  '🏉': '[BALL8]',
  '🥏': '[DISC]',
  '🎱': '[BALL9]',
  '🪀': '[YO]',
  '🏓': '[PONG]',
  '🏸': '[BADMINTON]',
  '🏒': '[HOCKEY]',
  '🏑': '[FIELD]',
  '🥍': '[LAX]',
  '🏏': '[CRICKET]',
  '🥅': '[GOAL]',
  '⛳': '[GOLF]',
  '🎣': '[FISH]',
  '🤿': '[DIVE]',
  '🥊': '[BOX]',
  '🥋': '[UNIFORM]',
  '🎽': '[SHIRT]',
  '🛹': '[SKATE]',
  '🛷': '[SLED]',
  '⛸️': '[SKATE2]',
  '🥌': '[CURL]',
  '🎿': '[SKI]',
  '⛷️': '[SKIER]',
  '🏂': '[BOARD]',
  '🪂': '[PARA]',
  '🏋️': '[LIFT]',
  '🤼': '[WRESTLE]',
  '🤸': '[CARTWHEEL]',
  '⛹️': '[BALL10]',
  '🤺': '[FENCE]',
  '🤾': '[HANDBALL]',
  '🏌️': '[GOLF2]',
  '🏇': '[HORSE]',
  '🧘': '[YOGA]',
  '🏄': '[SURF]',
  '🏊': '[SWIM]',
  '🤽': '[POLO]',
  '🚣': '[ROW]',
  '🧗': '[CLIMB]',
  '🚵': '[BIKE]',
  '🚴': '[BIKE2]',
  '🎖️': '[MEDAL2]',
  '🏵️': '[ROSETTE]',
  '🎗️': '[RIBBON2]',
  '🎫': '[TICKET]',
  '🎟️': '[TICKET2]',
  '🎪': '[CIRCUS]',
  '🤹': '[JUGGLE]',
  '🎭': '[MASK]',
  '🩰': '[BALLET]',
  '🎬': '[FILM]',
  '🎤': '[MIC]',
  '🎧': '[HEAD]',
  '🎼': '[MUSIC]',
  '🎹': '[PIANO]',
  '🥁': '[DRUM]',
  '🎷': '[SAX]',
  '🎺': '[TRUMPET]',
  '🎸': '[GUITAR]',
  '🪕': '[BANJO]',
  '🎻': '[VIOLIN]',
  '🎲': '[DICE]',
  '🎳': '[BOWL]',
  '🎮': '[GAME]',
  '🎰': '[SLOT]',
  '🧩': '[PUZZLE]',
  '⌨️': '[KEYBOARD]',
  '🖱️': '[MOUSE]',
  '🖲️': '[TRACK]',
  '💽': '[DISK]',
  '💾': '[FLOPPY]',
  '💿': '[CD]',
  '📀': '[DVD]',
  '🎥': '[CAM]',
  '📷': '[CAM2]',
  '📸': '[FLASH]',
  '📹': '[VIDEO]',
  '📼': '[TAPE]',
  '🔎': '[SEARCH2]',
  '💻': '[PC]',
  '🖥️': '[PC2]',
  '🖨️': '[PRINT]',
  '💯': '[100]',
  '💢': '[ANGER]',
  '💬': '[BUBBLE]',
  '👁️‍🗨️': '[EYE]',
  '🗨️': '[BUBBLE2]',
  '🗯️': '[BUBBLE3]',
  '💭': '[THOUGHT]',
  '💤': '[SLEEP]',
  '💮': '[FLOWER]',
  '♨️': '[HOT]',
  '💈': '[BARBER]',
  '🛑': '[STOP]',
  '🌀': '[CYCLONE]',
  '♠️': '[SPADE]',
  '♥️': '[HEART]',
  '♦️': '[DIAMOND]',
  '♣️': '[CLUB]',
  '🃏': '[JOKER]',
  '🀄': '[MAHJONG]',
  '🎴': '[CARDS]',
  '🔇': '[MUTE]',
  '🔈': '[VOL]',
  '🔉': '[VOL2]',
  '🔊': '[VOL3]',
  '📣': '[MEGA]',
  '📯': '[HORN]',
  '🔔': '[BELL2]',
  '🔕': '[NOBELL]',
  '🎵': '[NOTE]',
  '🎶': '[NOTES]',
  '🏧': '[ATM]',
  '🚮': '[LITTER]',
  '♿': '[WHEEL]',
  '🚹': '[MEN]',
  '🚺': '[WOMEN]',
  '🚻': '[REST]',
  '🚼': '[BABY]',
  '🚾': '[WC]',
  '🛂': '[PASS]',
  '🛃': '[CUSTOMS]',
  '🛄': '[BAG]',
  '🛅': '[LEFT]',
  '🚸': '[CHILD]',
  '⛔': '[NOENTRY]',
  '🚳': '[NOBIKE]',
  '🚭': '[NOSMOKE]',
  '🚯': '[NOLITTER]',
  '🚱': '[NOWATER]',
  '🚷': '[NOPED]',
  '📵': '[NOPHONE]',
  '🔞': '[NO18]',
  '☢️': '[RADIO]',
  '☣️': '[BIO]',
  '⬆️': '[UP5]',
  '↗️': '[NE]',
  '➡️': '[RIGHT]',
  '↘️': '[SE]',
  '⬇️': '[DOWN5]',
  '↙️': '[SW]',
  '⬅️': '[LEFT]',
  '↖️': '[NW]',
  '↕️': '[UPDOWN]',
  '↔️': '[LEFTRIGHT]',
  '↩️': '[UNDO]',
  '↪️': '[REDO]',
  '🔃': '[CYCLE]',
  '🔙': '[BACK]',
  '🔚': '[END]',
  '🔛': '[ON]',
  '🔜': '[SOON]',
  '🔝': '[TOP]',
  '🛐': '[WORSHIP]',
  '⚛️': '[ATOM]',
  '🕉️': '[OM]',
  '✡️': '[STAR]',
  '☸️': '[WHEEL]',
  '☯️': '[YIN]',
  '✝️': '[CROSS]',
  '☦️': '[ORTHODOX]',
  '☪️': '[STAR2]',
  '☮️': '[PEACE]',
  '🕎': '[MENORAH]',
  '🔯': '[STAR3]',
  '🔀': '[SHUFFLE]',
  '🔁': '[REPEAT2]',
  '🔂': '[REPEAT3]',
  '▶️': '[PLAY]',
  '⏩': '[FF]',
  '⏭️': '[NEXT]',
  '⏯️': '[PAUSE]',
  '◀️': '[REV]',
  '⏪': '[RW]',
  '⏮️': '[PREV]',
  '🔼': '[UP6]',
  '⏫': '[UP7]',
  '🔽': '[DOWN6]',
  '⏬': '[DOWN7]',
  '⏸️': '[PAUSE2]',
  '⏹️': '[STOP2]',
  '⏺️': '[REC]',
  '⏏️': '[EJECT]',
  '🎦': '[CINEMA]',
  '🔅': '[DIM]',
  '🔆': '[BRIGHT]',
  '📶': '[SIGNAL]',
  '📳': '[VIBRATE]',
  '📴': '[OFF]',
  '♀️': '[FEMALE]',
  '♂️': '[MALE]',
  '⚧️': '[TRANS]',
  '✖️': '[MULT]',
  '➕': '[PLUS]',
  '➖': '[MINUS]',
  '➗': '[DIV]',
  '♾️': '[INF]',
  '‼️': '[!!]',
  '⁉️': '[?!]',
  '❓': '[?]',
  '❔': '[?2]',
  '❕': '[!]',
  '❗': '[!!2]',
  '〰️': '[WAVE]',
  '💱': '[EXCH]',
  '💲': '[DOLLAR2]',
  '⚕️': '[MED]',
  '♻️': '[RECYCLE]',
  '⚜️': '[FLEUR]',
  '🔱': '[TRI]',
  '📛': '[BADGE]',
  '🔰': '[BEGIN]',
  '⭕': '[HEAVY]',
  '☑️': '[BOX]',
  '✔️': '[CHECK2]',
  '❎': '[X2]',
  '➰': '[LOOP]',
  '➿': '[LOOP2]',
  '〽️': '[PART]',
  '✳️': '[STAR4]',
  '✴️': '[STAR5]',
  '❇️': '[SPARKLE]',
  '©️': '[C]',
  '®️': '[R]',
  '™️': '[TM]',
  '#️⃣': '[HASH]',
  '*️⃣': '[STAR6]',
  '0️⃣': '[0]',
  '1️⃣': '[1]',
  '2️⃣': '[2]',
  '3️⃣': '[3]',
  '4️⃣': '[4]',
  '5️⃣': '[5]',
  '6️⃣': '[6]',
  '7️⃣': '[7]',
  '8️⃣': '[8]',
  '9️⃣': '[9]',
  '🔟': '[10]',
  '🔠': '[ABC]',
  '🔡': '[ABC2]',
  '🔢': '[123]',
  '🔣': '[SYM]',
  '🔤': '[ABC3]',
  '🅰️': '[A]',
  '🆎': '[AB]',
  '🅱️': '[B]',
  '🆑': '[CL]',
  '🆒': '[COOL]',
  '🆓': '[FREE]',
  'ℹ️': '[INFO]',
  '🆔': '[ID]',
  'Ⓜ️': '[M]',
  '🆕': '[NEW]',
  '🆖': '[NG]',
  '🅾️': '[O]',
  '🆗': '[OK2]',
  '🅿️': '[P]',
  '🆘': '[SOS]',
  '🆙': '[UP8]',
  '🆚': '[VS]',
  '🈁': '[KOKO]',
  '🈂️': '[SA]',
  '🈷️': '[MOON]',
  '🈶': '[HAVE]',
  '🈚': '[NOT]',
  '🈸': '[APPLY]',
  '🈴': '[PASS2]',
  '🈳': '[EMPTY]',
  '㊗️': '[CONG]',
  '㊙️': '[SECRET]',
  '🈺': '[OPEN2]',
  '🈵': '[FULL]',
  '🔴': '[RED]',
  '🟠': '[ORANGE]',
  '🟡': '[YELLOW]',
  '🟢': '[GREEN]',
  '🔵': '[BLUE]',
  '🟣': '[PURPLE]',
  '🟤': '[BROWN]',
  '⚫': '[BLACK]',
  '⚪': '[WHITE]',
  '🟥': '[RED2]',
  '🟧': '[ORANGE2]',
  '🟨': '[YELLOW2]',
  '🟩': '[GREEN2]',
  '🟦': '[BLUE2]',
  '🟪': '[PURPLE2]',
  '🟫': '[BROWN2]',
  '⬛': '[BLACK2]',
  '⬜': '[WHITE2]',
  '◼️': '[BLACK3]',
  '◻️': '[WHITE3]',
  '◾': '[BLACK4]',
  '◽': '[WHITE4]',
  '▪️': '[BLACK5]',
  '▫️': '[WHITE5]',
  '🔶': '[ORANGE3]',
  '🔷': '[BLUE3]',
  '🔸': '[ORANGE4]',
  '🔹': '[BLUE4]',
  '🔺': '[RED3]',
  '🔻': '[RED4]',
  '💠': '[DIAMOND]',
  '🔘': '[RADIO]',
  '🔳': '[SQUARE]',
  '🔲': '[SQUARE2]',
  '🏁': '[FLAG]',
  '🚩': '[FLAG2]',
  '🎌': '[FLAGS2]',
  '🏴': '[FLAG3]',
  '🏳️': '[FLAG4]',
  '🏳️‍🌈': '[RAINBOW]',
  '🏳️‍⚧️': '[TRANS]',
  '🏴‍☠️': '[PIRATE]'
};

function replaceEmoji(text: string): string {
  if (typeof text !== 'string') return text;
  let result = text;
  for (const [emoji, replacement] of Object.entries(emojiMap)) {
    result = result.split(emoji).join(replacement);
  }
  return result;
}

export class Logger {
  private logger: winston.Logger;

  constructor() {
    const fs = require('fs');
    const path = require('path');
    const logsDir = path.join(process.cwd(), 'logs');
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }

    const baseFormat = winston.format.printf(({ level, message, timestamp }) => {
      const cleanMessage = replaceEmoji(String(message));
      return `${timestamp} ${level}: ${cleanMessage}`;
    });

    this.logger = winston.createLogger({
      level: process.env.LOG_LEVEL || 'info',
      format: winston.format.combine(
        winston.format.timestamp(),
        winston.format.uncolorize()
      ),
      transports: [
        new winston.transports.Console({
          format: winston.format.combine(
            winston.format.timestamp(),
            winston.format.uncolorize(),
            baseFormat
          )
        }),
        new winston.transports.File({
          filename: 'logs/harness.log',
          format: winston.format.combine(
            winston.format.timestamp(),
            winston.format.uncolorize(),
            baseFormat
          ),
          options: { flags: 'a', encoding: 'utf8' }
        })
      ],
      exitOnError: false
    });
  }

  info(message: string, ...meta: any[]): void {
    this.logger.info(message, ...meta);
  }

  error(message: string, ...meta: any[]): void {
    this.logger.error(message, ...meta);
  }

  warn(message: string, ...meta: any[]): void {
    this.logger.warn(message, ...meta);
  }

  debug(message: string, ...meta: any[]): void {
    this.logger.debug(message, ...meta);
  }
}
