import { Logger } from '../utils/Logger';
import { PRAutomator } from './PRAutomator';
import { ReviewAgent } from './ReviewAgent';
import { PRWorkflowResult } from '../types/superpowers';

export class PRWorkflow {
  private logger: Logger;
  private prAutomator: PRAutomator;
  private reviewAgent: ReviewAgent;

  constructor() {
    this.logger = new Logger();
    this.prAutomator = new PRAutomator();
    this.reviewAgent = new ReviewAgent({
      provider: 'anthropic',
      model: 'kimi-for-coding',
      apiKey: process.env.KIMI_API_KEY || '',
      maxTokens: 128000,
      temperature: 0.2,
      timeout: 300000
    });
  }

  /**
   * Run complete PR workflow: create → review → (optional) merge
   */
  async run(task: any, codeResult: any): Promise<PRWorkflowResult> {
    this.logger.info(`🔀 Starting PR workflow for: ${task.title}`);

    // Step 1: Create PR
    const pr = await this.createPR(task, codeResult);
    if (!pr || pr.simulated) {
      return {
        prNumber: 0,
        prUrl: pr?.url || '',
        branch: codeResult.branch || '',
        reviewStatus: 'pending',
        merged: false
      };
    }

    // Step 2: Run Review
    const review = await this.runReview(pr.number);

    // Step 3: Auto-merge if approved and enabled
    let merged = false;
    if (review.status === 'approved' && review.canAutoApprove) {
      merged = await this.mergePR(pr.number);
    }

    return {
      prNumber: pr.number,
      prUrl: pr.url,
      branch: codeResult.branch,
      reviewStatus: review.status,
      merged
    };
  }

  /**
   * Create PR for the task
   */
  private async createPR(task: any, codeResult: any): Promise<any> {
    this.logger.info('📤 Creating PR...');
    
    try {
      const branch = codeResult.branch || `harness/${task.id}`;
      const pr = await this.prAutomator.create({
        branch,
        title: `[Auto] ${task.title}`,
        body: this.buildPRBody(task, codeResult),
        draft: false
      });

      this.logger.info(`✅ PR created: ${pr.url}`);
      return pr;
    } catch (error: any) {
      this.logger.error('❌ PR creation failed:', error.message);
      return null;
    }
  }

  /**
   * Run code review
   */
  private async runReview(prNumber: number): Promise<any> {
    this.logger.info(`🔍 Running review for PR #${prNumber}...`);
    
    try {
      const review = await this.reviewAgent.review(prNumber);
      this.logger.info(`📋 Review result: ${review.status}`);
      return review;
    } catch (error: any) {
      this.logger.error('❌ Review failed:', error.message);
      return { status: 'pending', canAutoApprove: false };
    }
  }

  /**
   * Merge PR
   */
  private async mergePR(prNumber: number): Promise<boolean> {
    this.logger.info(`🔀 Merging PR #${prNumber}...`);
    
    try {
      await this.prAutomator.merge({
        number: prNumber,
        strategy: 'squash',
        deleteBranch: true
      });
      this.logger.info('✅ PR merged');
      return true;
    } catch (error: any) {
      this.logger.error('❌ Merge failed:', error.message);
      return false;
    }
  }

  private buildPRBody(task: any, codeResult: any): string {
    return `## 🤖 Harness Auto-generated PR

**Task:** ${task.title}
**ID:** ${task.id}

### Summary
${codeResult.summary || 'Automated code generation and modifications'}

### Changes
- ${codeResult.files?.length || 0} files modified
- Duration: ${Math.round((codeResult.duration || 0) / 1000)}s

---
*Generated by Harness-Engineering with Superpowers*`;
  }
}
